name: Silentium-Greetings
version: 1.3.9
main: me.nockiee.silentiumgreetings.SilentGreetings   # <--- Переименовано
api-version: "1.21"
author: nockiee

commands:
  hi:
    description: "Приветствие игрока"
    aliases: [q, greeting, hi, hello]
  hug:
    description: "Обнять игрока"
    aliases: [neck, hg]
  f:
    description: "Почтить память игрока"
    alliases: [pressf, respect]
  bye:
    description: "Попрощаться с игроком"
    aliases: [goodbye, bb]
  five:
    description: "Дать пять игроку"
    aliases: [givefive, highfive]
  place:
    description: "Поделится своими координатами с игроком"
    aliases: [pos, location]
  kiss:
    description: "Поцеловать игрока поблизости либо отправить воздушный поцелуй"
    aliases: [airkiss, smooch]