name: Silentium-Greetings
version: 1.3.8
main: me.nockiee.silentiumgreetings.SilentiumGreetings
api-version: "1.21"
author: nockiee

commands:
  hi:
    description: "Приветствие игрока"
    aliases: [q, greeting, hi, hello]
  hug:
    description: "Обнять игрока"
    aliases: [neck, hg]
  f:
    description: "Почтить память"
    alliases: [pressf, respect]